/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rss.gui;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import rss.solution.*;

/**
 *
 * @author Admin
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    ProductDao pd = new ProductDao();
    UserDao ud = new UserDao();
    function f = new function();
    Admin a;
    
    String username, password;    
    
    public AdminHome(String username, String password) {
        initComponents();
        
        this.username = username;
        this.password = password;
        a = new Admin(username, password);
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(true);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
    }
    
    public AdminHome(){
        initComponents();
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(true);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tabHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tabProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabSignout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabMCust = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlNewAdmin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pnlCust = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlViewCust = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCustomer = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtSearchCust = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        pnlEditCust = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtNewPhone = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        btnDelCust = new javax.swing.JButton();
        btnUpdateCust = new javax.swing.JButton();
        txtNewMail = new javax.swing.JTextField();
        pnlAddCust = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCustId = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCustPass = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtCustMail = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCustPhone = new javax.swing.JTextField();
        btnReg = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlProduct = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtSProduct = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pnlEditProduct = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblProductId = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        txtNewPrice = new javax.swing.JTextField();
        txtQupdate = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNewDesc = new javax.swing.JTextArea();
        btnDeleteProduct = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        btnUpdateProduct = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        cboFragile = new javax.swing.JComboBox<>();
        pnlOrder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 80));
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(100, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(153, 204, 255));
        pnlMenu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        pnlMenu.setName(""); // NOI18N
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 500));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome back");
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopicon.jpg"))); // NOI18N
        pnlMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, 100));

        tabHome.setBackground(new java.awt.Color(204, 204, 204));
        tabHome.setPreferredSize(new java.awt.Dimension(0, 60));
        tabHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHomeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Admin Account");

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 60));

        tabProduct.setBackground(new java.awt.Color(204, 204, 204));
        tabProduct.setPreferredSize(new java.awt.Dimension(0, 60));
        tabProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProductMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Product");

        javax.swing.GroupLayout tabProductLayout = new javax.swing.GroupLayout(tabProduct);
        tabProduct.setLayout(tabProductLayout);
        tabProductLayout.setHorizontalGroup(
            tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tabProductLayout.setVerticalGroup(
            tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 60));

        tabOrder.setBackground(new java.awt.Color(204, 204, 204));
        tabOrder.setPreferredSize(new java.awt.Dimension(0, 60));
        tabOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabOrderMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Order List");

        javax.swing.GroupLayout tabOrderLayout = new javax.swing.GroupLayout(tabOrder);
        tabOrder.setLayout(tabOrderLayout);
        tabOrderLayout.setHorizontalGroup(
            tabOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabOrderLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tabOrderLayout.setVerticalGroup(
            tabOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 60));

        tabSignout.setBackground(new java.awt.Color(204, 204, 204));
        tabSignout.setPreferredSize(new java.awt.Dimension(0, 60));
        tabSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSignoutMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sign Out");

        javax.swing.GroupLayout tabSignoutLayout = new javax.swing.GroupLayout(tabSignout);
        tabSignout.setLayout(tabSignoutLayout);
        tabSignoutLayout.setHorizontalGroup(
            tabSignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSignoutLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tabSignoutLayout.setVerticalGroup(
            tabSignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSignoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabSignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 60));

        tabMCust.setBackground(new java.awt.Color(204, 204, 204));
        tabMCust.setPreferredSize(new java.awt.Dimension(0, 60));
        tabMCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMCustMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Manage Customer");

        javax.swing.GroupLayout tabMCustLayout = new javax.swing.GroupLayout(tabMCust);
        tabMCust.setLayout(tabMCustLayout);
        tabMCustLayout.setHorizontalGroup(
            tabMCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabMCustLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(35, 35, 35))
        );
        tabMCustLayout.setVerticalGroup(
            tabMCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMCustLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabMCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 60));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        pnlNewAdmin.setMaximumSize(new java.awt.Dimension(800, 650));
        pnlNewAdmin.setMinimumSize(new java.awt.Dimension(800, 650));
        pnlNewAdmin.setPreferredSize(new java.awt.Dimension(800, 650));
        pnlNewAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Elephant", 2, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("New Admin");
        pnlNewAdmin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 500, 80));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Username : ");
        pnlNewAdmin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel9.setText("Phone no. : ");
        pnlNewAdmin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("E-mail        : ");
        pnlNewAdmin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setText("Password  :");
        pnlNewAdmin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 40));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel12.setText("Account Type : ");
        pnlNewAdmin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 170, 40));

        lblAccType.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblAccType.setText("admin");
        pnlNewAdmin.add(lblAccType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 90, 50));
        pnlNewAdmin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 300, 40));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        pnlNewAdmin.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 300, 40));
        pnlNewAdmin.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 300, 40));
        pnlNewAdmin.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 300, 40));

        btnAdd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        pnlNewAdmin.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 210, 60));

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlNewAdmin.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 200, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/register2.png"))); // NOI18N
        pnlNewAdmin.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        jPanel1.add(pnlNewAdmin);

        pnlCust.setBackground(new java.awt.Color(204, 204, 204));
        pnlCust.setMaximumSize(new java.awt.Dimension(800, 650));
        pnlCust.setMinimumSize(new java.awt.Dimension(800, 650));
        pnlCust.setPreferredSize(new java.awt.Dimension(800, 650));
        pnlCust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Manage Customer");
        pnlCust.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 450, 50));

        pnlViewCust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Password", "Account Type", "E-mail", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCustomer.getTableHeader().setReorderingAllowed(false);
        tbCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCustomer);
        if (tbCustomer.getColumnModel().getColumnCount() > 0) {
            tbCustomer.getColumnModel().getColumn(0).setResizable(false);
            tbCustomer.getColumnModel().getColumn(1).setResizable(false);
            tbCustomer.getColumnModel().getColumn(2).setResizable(false);
            tbCustomer.getColumnModel().getColumn(3).setResizable(false);
            tbCustomer.getColumnModel().getColumn(4).setResizable(false);
        }

        pnlViewCust.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 670, 300));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Search Customer :");
        pnlViewCust.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 130, 40));

        txtSearchCust.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        txtSearchCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCustKeyReleased(evt);
            }
        });
        pnlViewCust.add(txtSearchCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 190, 40));

        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel39.setText("Select a customer in table to edit");
        pnlViewCust.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTabbedPane1.addTab("View Customer", pnlViewCust);

        pnlEditCust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Edit Customer");
        pnlEditCust.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 260, 40));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel38.setText("Selected Customer username:");
        pnlEditCust.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 58, 260, 46));

        lblUserName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        pnlEditCust.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 58, 195, 45));

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel40.setText("Password             :");
        pnlEditCust.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 129, 49));
        pnlEditCust.add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 40));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel41.setText("Phone                  :");
        pnlEditCust.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 219, 120, 40));

        txtNewPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPhoneKeyTyped(evt);
            }
        });
        pnlEditCust.add(txtNewPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 220, 40));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel42.setText("E-mail                  :");
        pnlEditCust.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 129, 40));

        btnDelCust.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnDelCust.setText("Delete");
        btnDelCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelCustMouseClicked(evt);
            }
        });
        pnlEditCust.add(btnDelCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 130, 80));

        btnUpdateCust.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnUpdateCust.setText("Update");
        btnUpdateCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateCustMouseClicked(evt);
            }
        });
        pnlEditCust.add(btnUpdateCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 130, 80));
        pnlEditCust.add(txtNewMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 220, 40));

        jTabbedPane1.addTab("Edit Customer", pnlEditCust);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Add New Customer");

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel21.setText("Username :");

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel22.setText("Password :");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel23.setText("E - mail    :");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel24.setText("Phone      :");

        txtCustPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustPhoneKeyTyped(evt);
            }
        });

        btnReg.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnReg.setText("Register");
        btnReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegMouseClicked(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnClear.setText("Cancel");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAddCustLayout = new javax.swing.GroupLayout(pnlAddCust);
        pnlAddCust.setLayout(pnlAddCustLayout);
        pnlAddCustLayout.setHorizontalGroup(
            pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCustLayout.createSequentialGroup()
                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddCustLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAddCustLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtCustPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlAddCustLayout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtCustMail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlAddCustLayout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtCustPass, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAddCustLayout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnlAddCustLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddCustLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        pnlAddCustLayout.setVerticalGroup(
            pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCustLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustPass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustMail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", pnlAddCust);

        pnlCust.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 750, 510));

        jPanel1.add(pnlCust);

        pnlProduct.setBackground(new java.awt.Color(204, 204, 204));
        pnlProduct.setMaximumSize(new java.awt.Dimension(800, 650));
        pnlProduct.setMinimumSize(new java.awt.Dimension(800, 650));
        pnlProduct.setPreferredSize(new java.awt.Dimension(800, 650));
        pnlProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Manage Product");
        pnlProduct.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 0, 500, 61));

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Produc Name", "Description", "Fragile", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProduct.getTableHeader().setReorderingAllowed(false);
        tbProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProduct);
        if (tbProduct.getColumnModel().getColumnCount() > 0) {
            tbProduct.getColumnModel().getColumn(0).setResizable(false);
            tbProduct.getColumnModel().getColumn(1).setResizable(false);
            tbProduct.getColumnModel().getColumn(2).setResizable(false);
            tbProduct.getColumnModel().getColumn(3).setResizable(false);
            tbProduct.getColumnModel().getColumn(4).setResizable(false);
            tbProduct.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel15.setText("Search Product :");

        txtSProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSProductKeyReleased(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel29.setText("Select a product in table to edit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jTabbedPane2.addTab("View Product", jPanel2);

        pnlEditProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel19.setText("Your Chosen Product ID:");
        pnlEditProduct.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 212, 49));

        lblProductId.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        pnlEditProduct.add(lblProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 230, 50));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel25.setText("Name                    :");
        pnlEditProduct.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 129, 51));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel26.setText("Description         :");
        pnlEditProduct.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 129, 49));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel27.setText("Price                     :");
        pnlEditProduct.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 129, 49));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel28.setText("Quantity Update :");
        pnlEditProduct.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 129, 49));
        pnlEditProduct.add(txtNewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 220, 40));

        txtNewPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewPriceKeyTyped(evt);
            }
        });
        pnlEditProduct.add(txtNewPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 220, 40));

        txtQupdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQupdateKeyTyped(evt);
            }
        });
        pnlEditProduct.add(txtQupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 220, 40));

        txtNewDesc.setColumns(20);
        txtNewDesc.setRows(5);
        jScrollPane3.setViewportView(txtNewDesc);

        pnlEditProduct.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 220, 130));

        btnDeleteProduct.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnDeleteProduct.setText("Delete");
        btnDeleteProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteProductMouseClicked(evt);
            }
        });
        pnlEditProduct.add(btnDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 130, 80));

        jLabel36.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Edit Product");
        pnlEditProduct.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 260, -1));

        btnUpdateProduct.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnUpdateProduct.setText("Update");
        btnUpdateProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateProductMouseClicked(evt);
            }
        });
        pnlEditProduct.add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 130, 80));

        jTabbedPane2.addTab("Edit Product", pnlEditProduct);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel30.setText("Fragile              :");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, 40));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel31.setText("Product Name  :");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 119, 43));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel32.setText("Description     :");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 103, 50));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel33.setText("Price                 :");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 119, 43));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel34.setText("Quantity          :");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 110, 40));

        jLabel35.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Add New Product");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 21, 301, 49));
        jPanel4.add(txtPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 240, 43));
        jPanel4.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 240, 43));
        jPanel4.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 43));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane4.setViewportView(txtDesc);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 240, 80));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("Cancel");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 130, 60));

        btnNewProduct.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnNewProduct.setText("Add");
        btnNewProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewProductMouseClicked(evt);
            }
        });
        jPanel4.add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 130, 60));

        cboFragile.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        cboFragile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non-Fragile", "Fragile" }));
        jPanel4.add(cboFragile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 160, 30));

        jTabbedPane2.addTab("Add Product", jPanel4);

        pnlProduct.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 72, -1, -1));

        jPanel1.add(pnlProduct);

        pnlOrder.setBackground(new java.awt.Color(255, 255, 204));
        pnlOrder.setMinimumSize(new java.awt.Dimension(800, 650));
        pnlOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnlOrder);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void tabHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHomeMouseClicked
        pnlNewAdmin.setVisible(true);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
        tabHome.setBackground(Color.WHITE);
        tabProduct.setBackground(new Color (204,204,204));
        tabOrder.setBackground(new Color (204,204,204));
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(new Color (204,204,204));
    }//GEN-LAST:event_tabHomeMouseClicked

    private void tabProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductMouseClicked
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(true);
        pnlCust.setVisible(false);
        tabHome.setBackground(new Color (204,204,204));
        tabProduct.setBackground(Color.WHITE);
        tabOrder.setBackground(new Color (204,204,204));
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(new Color (204,204,204));
        
        f.updateTable(tbProduct,pd.getProductList());
        jTabbedPane2.setEnabledAt(1, false);

    }//GEN-LAST:event_tabProductMouseClicked

    private void tabOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabOrderMouseClicked
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(true);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
        tabHome.setBackground(new Color (204,204,204));
        tabProduct.setBackground(new Color (204,204,204));
        tabOrder.setBackground(Color.white);
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(new Color (204,204,204));

    }//GEN-LAST:event_tabOrderMouseClicked
 
    private void tabSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSignoutMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_tabSignoutMouseClicked

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        String userName, password, email;
        int phone;


        if(txtUser.getText().isEmpty()| txtPass.getText().isEmpty() |
            txtEmail.getText().isEmpty()|txtPhone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Missing Information!","Fail ", JOptionPane.ERROR_MESSAGE);
        }else
        {
            userName = txtUser.getText();
            password = txtPass.getText();
            email = txtEmail.getText();
            phone = Integer.parseInt(txtPhone.getText());
            if(a.addAdmin(userName, password, email, phone))
            {
                JOptionPane.showMessageDialog(null,"Register Sccessful","Successful", 1);
                txtUser.setText("");
                txtPhone.setText("");
                txtEmail.setText("");
                txtPass.setText("");
            } else
            {
                JOptionPane.showMessageDialog(null,"Register Fail, username exist","Fail ", JOptionPane.ERROR_MESSAGE);
                txtUser.setText("");
                txtPhone.setText("");
                txtEmail.setText("");
                txtPass.setText("");
            }
        }

    }//GEN-LAST:event_btnAddMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        txtUser.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnCancelMouseClicked

    private void tabMCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMCustMouseClicked
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(true);
        tabHome.setBackground(new Color (204,204,204));
        tabProduct.setBackground(new Color (204,204,204));
        tabOrder.setBackground(new Color (204,204,204));
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(Color.white);
        
        f.updateCustTable(tbCustomer,ud.getUserList());
        jTabbedPane1.setEnabledAt(1, false);
    }//GEN-LAST:event_tabMCustMouseClicked

    private void btnRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegMouseClicked
        String userName, password, email;
        int phone;

        UserDao u = new UserDao();
        
         if(txtCustId.getText().isEmpty()| txtCustPass.getText().isEmpty() |
            txtCustMail.getText().isEmpty()|txtCustPhone.getText().isEmpty())
         {
            JOptionPane.showMessageDialog(null,"Missing Information!","Fail ", JOptionPane.ERROR_MESSAGE);
         }else
         {
            userName = txtCustId.getText();
            password = txtCustPass.getText();
            email = txtCustMail.getText();
            phone = Integer.parseInt(txtCustPhone.getText());
                if(u.addUser(userName, password,"Customer", email,phone))
            {
                JOptionPane.showMessageDialog(null,"Register Sccessful","Successful", 1);
                txtCustId.setText("");
                txtCustPass.setText("");
                txtCustMail.setText("");
                txtCustPhone.setText("");
                
                f.updateCustTable(tbCustomer, ud.getUserList());
            } else
            {
                JOptionPane.showMessageDialog(null,"Register Fail, username exist","Fail ", JOptionPane.ERROR_MESSAGE);    
                txtCustId.setText("");
                txtCustPass.setText("");
                txtCustMail.setText("");
                txtCustPhone.setText("");
            }
         }
    }//GEN-LAST:event_btnRegMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        txtCustId.setText("");
        txtCustMail.setText("");
        txtCustPass.setText("");
        txtCustPhone.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void txtCustPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustPhoneKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCustPhoneKeyTyped

    private void tbProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductMouseClicked
        int index = tbProduct.getSelectedRow();
        TableModel model = tbProduct.getModel();
        String ProductId = model.getValueAt(index, 0).toString();
        

        if(!ProductId.isEmpty())
        {
            pd.getProduct(ProductId);
            jTabbedPane2.setSelectedIndex(1);
            lblProductId.setText(ProductId);
        }
        
    }//GEN-LAST:event_tbProductMouseClicked

    private void btnDeleteProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteProductMouseClicked
        int response = JOptionPane.showConfirmDialog(null,"Are You Sure Want to Delete ?","Confirmation", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION)
        {
            a.deleteProduct(pd.p.getId());
            f.updateTable(tbProduct,pd.getProductList());
        }
    
    }//GEN-LAST:event_btnDeleteProductMouseClicked

    private void txtNewPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPriceKeyTyped
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNewPriceKeyTyped

    private void txtQupdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQupdateKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQupdateKeyTyped

    private void btnUpdateProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateProductMouseClicked
        String name,desc;
        int quantity = 0;
        double price = 0;
        
        pd.getProduct(lblProductId.getText());
        name = txtNewName.getText();
        desc = txtNewDesc.getText();
        
        if(txtNewName.getText().isEmpty())
         {
            name = pd.p.getName();
         }
        
        if(txtNewDesc.getText().isEmpty())
        {
            desc = pd.p.getDescription();
        }
        
        if(txtQupdate.getText().isEmpty())
        {
            quantity = pd.p.getQuantity();
            String tempQuantity = String.valueOf(quantity);
            txtQupdate.setText(tempQuantity);
        }
        
        if(txtNewPrice.getText().isEmpty())
        {
            price = pd.p.getPrice();
            String tempPrice = String.valueOf(price);
            txtNewPrice.setText(tempPrice);
        }
         
        try
        {
            price =Double.parseDouble(txtNewPrice.getText()) ;
            quantity = Integer.parseInt(txtQupdate.getText());
            DecimalFormat df = new DecimalFormat("###.##");
            df.format(price);
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Invalid Number Input, Please try again !","Fail", 0);
        }
                
        if (!a.updateProduct(pd.p.getId(),name,desc,pd.p.getFragile(),quantity,price))
        {
            JOptionPane.showMessageDialog(null,"Update Fail, Please try again !","Fail", 3);
            txtNewName.setText("");
            txtQupdate.setText("");
            txtNewDesc.setText("");
            txtNewPrice.setText("");
        }else
        {
            JOptionPane.showMessageDialog(null,"Update Complete!","Success", 1);
            f.updateTable(tbProduct,pd.getProductList());
            txtNewName.setText("");
            txtQupdate.setText("");
            txtNewDesc.setText("");
            txtNewPrice.setText("");
        }
    }//GEN-LAST:event_btnUpdateProductMouseClicked

    private void btnNewProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewProductMouseClicked
        String Name, Description, isFragile;
        Boolean fragile;
        int quantity;
        double price;
        
        isFragile = cboFragile.getSelectedItem().toString();
        if(isFragile.equals("Fragile"))
        {
            fragile = true;
        }else
        {
            fragile = false;
        }
        
        if(txtPName.getText().isEmpty()| txtPrice.getText().isEmpty() |
            txtQuantity.getText().isEmpty()|txtDesc.getText().isEmpty())
         {
            JOptionPane.showMessageDialog(null,"Missing Information!","Fail ", JOptionPane.ERROR_MESSAGE);
         }else
        {
            Name = txtPName.getText();
            Description = txtDesc.getText();
            quantity = Integer.parseInt(txtQuantity.getText());
            price = Double.parseDouble(txtPrice.getText());
            
            if(a.addProduct(Name, Description, fragile, quantity, price))
            {
                JOptionPane.showMessageDialog(null,"Register Sccessful","Successful", 1);
                f.updateTable(tbProduct, pd.getProductList());
                txtPName.setText("");
                txtPrice.setText("");
                txtQuantity.setText("");
                txtDesc.setText("");
            }
        }
    }//GEN-LAST:event_btnNewProductMouseClicked

    private void txtSProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSProductKeyReleased
          f.search(tbProduct,txtSProduct.getText());
    }//GEN-LAST:event_txtSProductKeyReleased

    private void tbCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCustomerMouseClicked
        int index = tbCustomer.getSelectedRow();
        TableModel model = tbCustomer.getModel();
        String Id = model.getValueAt(index, 0).toString();
        String pass = model.getValueAt(index, 1).toString();
        
        if(!Id.isEmpty())
        {
            ud.findUser(Id,pass, "Customer", "find");
            jTabbedPane1.setSelectedIndex(1);
            lblUserName.setText(Id);
        }
    }//GEN-LAST:event_tbCustomerMouseClicked

    private void txtNewPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPhoneKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNewPhoneKeyTyped

    private void btnDelCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelCustMouseClicked
        int response = JOptionPane.showConfirmDialog(null,"Are You Sure Want to Delete ?","Confirmation", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION)
        {
            a.deleteUser(ud.c.getUsername(), ud.c.getaccountType());
            f.updateCustTable(tbCustomer,ud.getUserList());
        }
    }//GEN-LAST:event_btnDelCustMouseClicked

    private void btnUpdateCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateCustMouseClicked
        String pass,email,phone;
        
        pass = txtNewPass.getText().toLowerCase();
        email = txtNewMail.getText().toLowerCase();
        phone =txtNewPhone.getText().toLowerCase();
        
        if(txtNewPass.getText().isEmpty())
         {
            pass = ud.c.getPassword();
         }
        
        if(txtNewMail.getText().isEmpty())
        {
            email = ud.c.getEmail();
        }
        
        if(txtNewPhone.getText().isEmpty())
        {
            phone = String.valueOf(ud.c.getPhone());
            txtNewPhone.setText(phone);
        }
        
        if (!a.updateCustomer(ud.c.getUsername(), pass, email, Integer.parseInt(phone)))
        {
            JOptionPane.showMessageDialog(null,"Update Fail, Please try again !","Fail", 3);
        }else
        {
            JOptionPane.showMessageDialog(null,"Update Complete!","Success", 1);
            f.updateCustTable(tbCustomer, ud.getUserList());
            txtNewPhone.setText("");
            txtNewMail.setText("");
            txtNewPass.setText("");
        }
    }//GEN-LAST:event_btnUpdateCustMouseClicked

    private void txtSearchCustKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCustKeyReleased
        f.search(tbCustomer, txtSearchCust.getText());
    }//GEN-LAST:event_txtSearchCustKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelCust;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnUpdateCust;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JComboBox<String> cboFragile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlAddCust;
    private javax.swing.JPanel pnlCust;
    private javax.swing.JPanel pnlEditCust;
    private javax.swing.JPanel pnlEditProduct;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNewAdmin;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlViewCust;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabMCust;
    private javax.swing.JPanel tabOrder;
    private javax.swing.JPanel tabProduct;
    private javax.swing.JPanel tabSignout;
    private javax.swing.JTable tbCustomer;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtCustMail;
    private javax.swing.JTextField txtCustPass;
    private javax.swing.JTextField txtCustPhone;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtNewDesc;
    private javax.swing.JTextField txtNewMail;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtNewPhone;
    private javax.swing.JTextField txtNewPrice;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQupdate;
    private javax.swing.JTextField txtSProduct;
    private javax.swing.JTextField txtSearchCust;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
