/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rss.gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import rss.solution.*;

/**
 *
 * @author Admin
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tabHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tabProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tabOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tabSignout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tabMCust = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlCust = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlViewCust = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtSearchCust = new javax.swing.JTextField();
        btnSearchOrder = new javax.swing.JButton();
        pnlEditCust = new javax.swing.JPanel();
        pnlAddCust = new javax.swing.JPanel();
        pnlNewAdmin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pnlProduct = new javax.swing.JPanel();
        pnlOrder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 80));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(153, 204, 255));
        pnlMenu.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        pnlMenu.setName(""); // NOI18N
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 500));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome back");
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shopicon.jpg"))); // NOI18N
        pnlMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, 100));

        tabHome.setBackground(new java.awt.Color(204, 204, 204));
        tabHome.setPreferredSize(new java.awt.Dimension(0, 60));
        tabHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabHomeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Admin Account");

        javax.swing.GroupLayout tabHomeLayout = new javax.swing.GroupLayout(tabHome);
        tabHome.setLayout(tabHomeLayout);
        tabHomeLayout.setHorizontalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        tabHomeLayout.setVerticalGroup(
            tabHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 60));

        tabProduct.setBackground(new java.awt.Color(204, 204, 204));
        tabProduct.setPreferredSize(new java.awt.Dimension(0, 60));
        tabProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProductMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Product");

        javax.swing.GroupLayout tabProductLayout = new javax.swing.GroupLayout(tabProduct);
        tabProduct.setLayout(tabProductLayout);
        tabProductLayout.setHorizontalGroup(
            tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tabProductLayout.setVerticalGroup(
            tabProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 60));

        tabOrder.setBackground(new java.awt.Color(204, 204, 204));
        tabOrder.setPreferredSize(new java.awt.Dimension(0, 60));
        tabOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabOrderMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View Order List");

        javax.swing.GroupLayout tabOrderLayout = new javax.swing.GroupLayout(tabOrder);
        tabOrder.setLayout(tabOrderLayout);
        tabOrderLayout.setHorizontalGroup(
            tabOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabOrderLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tabOrderLayout.setVerticalGroup(
            tabOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 60));

        tabSignout.setBackground(new java.awt.Color(204, 204, 204));
        tabSignout.setPreferredSize(new java.awt.Dimension(0, 60));
        tabSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSignoutMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sign Out");

        javax.swing.GroupLayout tabSignoutLayout = new javax.swing.GroupLayout(tabSignout);
        tabSignout.setLayout(tabSignoutLayout);
        tabSignoutLayout.setHorizontalGroup(
            tabSignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSignoutLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tabSignoutLayout.setVerticalGroup(
            tabSignoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSignoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabSignout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 60));

        tabMCust.setBackground(new java.awt.Color(204, 204, 204));
        tabMCust.setPreferredSize(new java.awt.Dimension(0, 60));
        tabMCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMCustMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Manage Customer");

        javax.swing.GroupLayout tabMCustLayout = new javax.swing.GroupLayout(tabMCust);
        tabMCust.setLayout(tabMCustLayout);
        tabMCustLayout.setHorizontalGroup(
            tabMCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabMCustLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(35, 35, 35))
        );
        tabMCustLayout.setVerticalGroup(
            tabMCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabMCustLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(tabMCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 60));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        pnlCust.setBackground(new java.awt.Color(153, 153, 255));
        pnlCust.setMaximumSize(new java.awt.Dimension(800, 650));
        pnlCust.setMinimumSize(new java.awt.Dimension(800, 650));
        pnlCust.setPreferredSize(new java.awt.Dimension(800, 650));
        pnlCust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Manage Customer");
        pnlCust.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 450, 50));

        pnlViewCust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlViewCust.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 670, 340));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Customer   ID :");
        pnlViewCust.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 110, 32));

        txtSearchCust.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        pnlViewCust.add(txtSearchCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 190, 40));

        btnSearchOrder.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnSearchOrder.setText("Search");
        pnlViewCust.add(btnSearchOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 100, 40));

        jTabbedPane1.addTab("View Customer", pnlViewCust);

        javax.swing.GroupLayout pnlEditCustLayout = new javax.swing.GroupLayout(pnlEditCust);
        pnlEditCust.setLayout(pnlEditCustLayout);
        pnlEditCustLayout.setHorizontalGroup(
            pnlEditCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        pnlEditCustLayout.setVerticalGroup(
            pnlEditCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Edit Customer", pnlEditCust);

        javax.swing.GroupLayout pnlAddCustLayout = new javax.swing.GroupLayout(pnlAddCust);
        pnlAddCust.setLayout(pnlAddCustLayout);
        pnlAddCustLayout.setHorizontalGroup(
            pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        pnlAddCustLayout.setVerticalGroup(
            pnlAddCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add Customer", pnlAddCust);

        pnlCust.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 750, 510));

        jPanel1.add(pnlCust);

        pnlNewAdmin.setMinimumSize(new java.awt.Dimension(600, 504));
        pnlNewAdmin.setPreferredSize(new java.awt.Dimension(600, 500));
        pnlNewAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Elephant", 2, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("New Admin");
        pnlNewAdmin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 500, 80));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel8.setText("Username : ");
        pnlNewAdmin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel9.setText("Phone no. : ");
        pnlNewAdmin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("E-mail        : ");
        pnlNewAdmin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, 40));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setText("Password  :");
        pnlNewAdmin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 40));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel12.setText("Account Type : ");
        pnlNewAdmin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 170, 40));

        lblAccType.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblAccType.setText("admin");
        pnlNewAdmin.add(lblAccType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 90, 50));
        pnlNewAdmin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 300, 40));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        pnlNewAdmin.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 300, 40));
        pnlNewAdmin.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 300, 40));
        pnlNewAdmin.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 300, 40));

        btnAdd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        pnlNewAdmin.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 210, 60));

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        pnlNewAdmin.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 200, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/register2.png"))); // NOI18N
        pnlNewAdmin.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        jPanel1.add(pnlNewAdmin);

        pnlProduct.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout pnlProductLayout = new javax.swing.GroupLayout(pnlProduct);
        pnlProduct.setLayout(pnlProductLayout);
        pnlProductLayout.setHorizontalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlProductLayout.setVerticalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel1.add(pnlProduct);

        pnlOrder.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel1.add(pnlOrder);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabHomeMouseClicked
        pnlNewAdmin.setVisible(true);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
        tabHome.setBackground(Color.WHITE);
        tabProduct.setBackground(new Color (204,204,204));
        tabOrder.setBackground(new Color (204,204,204));
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(new Color (204,204,204));
    }//GEN-LAST:event_tabHomeMouseClicked

    private void tabProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductMouseClicked
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(true);
        pnlCust.setVisible(false);
        tabHome.setBackground(new Color (204,204,204));
        tabProduct.setBackground(Color.WHITE);
        tabOrder.setBackground(new Color (204,204,204));
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(new Color (204,204,204));
    }//GEN-LAST:event_tabProductMouseClicked

    private void tabOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabOrderMouseClicked
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(true);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(false);
        tabHome.setBackground(new Color (204,204,204));
        tabProduct.setBackground(new Color (204,204,204));
        tabOrder.setBackground(Color.white);
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(new Color (204,204,204));

    }//GEN-LAST:event_tabOrderMouseClicked


    
    private void tabSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSignoutMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_tabSignoutMouseClicked

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        String userName, password, email;
        int phone;

        UserDao u = new UserDao();

        if(txtUser.getText().isEmpty()| txtPass.getText().isEmpty() |
            txtEmail.getText().isEmpty()|txtPhone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Missing Information!","Fail ", JOptionPane.ERROR_MESSAGE);
        }else
        {
            userName = txtUser.getText();
            password = txtPass.getText();
            email = txtEmail.getText();
            phone = Integer.parseInt(txtPhone.getText());
            if(u.addUser(userName, password,"Admin", email,phone))
            {
                JOptionPane.showMessageDialog(null,"Register Sccessful","Successful", 1);
            } else
            {
                JOptionPane.showMessageDialog(null,"Register Fail, username exist","Fail ", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnAddMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        txtUser.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnCancelMouseClicked

    private void tabMCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMCustMouseClicked
        pnlNewAdmin.setVisible(false);
        pnlOrder.setVisible(false);
        pnlProduct.setVisible(false);
        pnlCust.setVisible(true);
        tabHome.setBackground(new Color (204,204,204));
        tabProduct.setBackground(new Color (204,204,204));
        tabOrder.setBackground(new Color (204,204,204));
        tabSignout.setBackground(new Color (204,204,204));
        tabMCust.setBackground(Color.white);
    }//GEN-LAST:event_tabMCustMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JPanel pnlAddCust;
    private javax.swing.JPanel pnlCust;
    private javax.swing.JPanel pnlEditCust;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNewAdmin;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlViewCust;
    private javax.swing.JPanel tabHome;
    private javax.swing.JPanel tabMCust;
    private javax.swing.JPanel tabOrder;
    private javax.swing.JPanel tabProduct;
    private javax.swing.JPanel tabSignout;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearchCust;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
