/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rss.gui;

import javax.swing.JOptionPane;
import rss.solution.*;

/**
 *
 * @author anvegave
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                cboRole = new javax.swing.JComboBox<>();
                txtPass = new javax.swing.JTextField();
                txtId = new javax.swing.JTextField();
                btnRegister = new javax.swing.JButton();
                btnLogin = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocation(new java.awt.Point(300, 100));
                setMinimumSize(new java.awt.Dimension(830, 540));
                setPreferredSize(new java.awt.Dimension(800, 500));

                jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel4.setFont(new java.awt.Font("Elephant", 2, 36)); // NOI18N
                jLabel4.setText("Anvegave Retail Store");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 420, 90));

                jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
                jLabel2.setText("Role         : ");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

                jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
                jLabel3.setText("Username : ");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

                jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
                jLabel5.setText("Password : ");
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

                cboRole.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
                cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Admin" }));
                jPanel1.add(cboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 130, 30));
                jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 260, 30));
                jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 260, 30));

                btnRegister.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
                btnRegister.setText("Register");
                btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnRegisterMouseClicked(evt);
                        }
                });
                jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 140, 40));

                btnLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
                btnLogin.setText("Sign In");
                btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnLoginMouseClicked(evt);
                        }
                });
                jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 140, 40));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.jpg"))); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 800, 500));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        this.setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String Id, password, role;
        Boolean verify;
        
        Customer c;
        Admin a;
        
        Id = txtId.getText().toLowerCase();
        password = txtPass.getText().toLowerCase();
        role = cboRole.getSelectedItem().toString();
        
        if (role == "Customer") 
        {
           c = new Customer(Id, password);
           verify = c.login();
           if (verify)
          {
                this.setVisible(false);
                new Store().setVisible(true);
          }
        }else 
        {
            a = new Admin(Id, password);
           verify = a.login();
           if (verify)
          {
                this.setVisible(false);
                new Store().setVisible(true);
          }
        }
        
        if (!verify)
        {
            JOptionPane.showMessageDialog(null,"Invalid Username or Password, Please Try Again","Fail ", 2); 
            txtId.setText("");
            txtPass.setText("");
        }
        
        
        
               
    }//GEN-LAST:event_btnLoginMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnLogin;
        private javax.swing.JButton btnRegister;
        private javax.swing.JComboBox<String> cboRole;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField txtId;
        private javax.swing.JTextField txtPass;
        // End of variables declaration//GEN-END:variables
}
